language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - "pip install flask six" 
  - "pip install pep8 coveralls nose"

script:
  - "nosetests --with-coverage --cover-package=flask_cors"
  - "python setup.py build install"
  - "nosetests"

after_success:
  - "pep8 flask_cors.py"
  - "coveralls"