language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - "pip install pep8"
  - "pip install flask nose six"

script:
  - "nosetests"
  - "pep8 flask_cors.py"
  - "python setup.py build install"
  - "nosetests"