language: python
python:
- '2.6'
- '2.7'
- '3.3'
- pypy
env:
- FLASK=0.10.1
- FLASK=0.10
- FLASK=0.9
matrix:
  allow_failures:
  - python: '3.3'
    env: FLASK=0.9
install:
- pip install pep8 coveralls six
- pip install -U "pip>=1.4" "setuptools>=0.9" "wheel>=0.21"
- pip install flask==$FLASK
script:
- coverage erase
- nosetests --with-coverage --cover-package=flask_cors
- python setup.py clean build install
after_success:
- pep8 flask_cors.py
- coveralls
deploy:
  provider: pypi
  user: CoryDolphin
  password:
    secure: KKc5C87ER7cCrOLLkPqiawmoYNngJfOLv9Plpj32u6R8fMIBYV11HUj2GmSOX3jho8nuNDX+9QitVpcKFdh7GkDaMYWTz4sWdGfUuz+uLTK5TETnm+FeuXGreNTla1QR+8JmEjY92H0OJPIkHAKOlJyNhxJ80OQfhOkgZdVfT9c=
  on:
    tags: true
    repo: corydolphin/flask-cors
